---
# tasks file for wordops

- name: install pip3
  apt:
    name: python3-pip
    update_cache: yes

- name: install pexpect
  pip:
    name: pexpect

- name: check that WO file exist, before checking WO status
  stat:
    path: /usr/local/bin/wo
  register: wo_stat

- name: download wo file
  get_url:
    url: http://wops.cc
    dest: /tmp/wo
  register: wo_download
  when: wo_stat.stat.exists == False

- name: install wo
  expect:
    command: /bin/bash /tmp/wo
    timeout: 600
    responses:
      'Enter your name:': "{{ wo_name }}"
      'Enter your email:': "{{ wo_email }}"
  register: wo_install
  when: not wo_download is skipped

#TODO add autocompletion /etc/bash_completion.d/wo_auto.rc to bash profile

- name: Check wo stack status
  command: wo stack status --nginx "{{ wo_mysql }}" --"{{ wo_phpversion }}" --wpcli
  register: wo_stack_status

- name: install wo stack
  command: wo stack install --nginx "{{ wo_mysql }}" --"{{ wo_phpversion }}" --wpcli
  register: wo_stack_install
  when: wo_stack_status.stdout.count('not installed') > 1

- name: Disable config cache on php-fpm
  command: for PHP in '7.2' '7.3' '7.4' ; do sed -i 's/php_admin_value/;php_admin_value/g' /etc/php/$PHP/fpm/pool.d/*.conf; done;
  register: disable_config_cache_on_php-fpm

# service section
- name: Enable and restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: not wo_stack_install is skipped

- name: Enable and restart "{{ wo_phpfpm }}"
  service:
    name: "{{ wo_phpfpm }}"
    state: restarted
    enabled: yes
  when: not wo_stack_install is skipped

- name: Enable and restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: not wo_stack_install is skipped
