name: Ansible lint

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Play Ansible Playbook
      uses: arillso/action.playbook@master
      with:
        playbook: site.yml
        # inventory: tests/hosts.yml
        # galaxy_file: tests/requirements.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'